{
 "title": "Freezer Monitoring System",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "model_name",
    "label": "Freezer Model",
    "query": "SELECT \"freezer_model\" FROM \"autogen\".\"freezer\" "
   }
  ]
 },
 "panels": [
  { "title": "Trend Plot", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "yaxes": [
    { "format": "celsius", "label": "Temperature" }
   ],
   "targets": [
    {
     "alias": "Temperature - ${model_name}",
     "measurement": "freezer",
     "query": "SELECT \"temp_value\" FROM \"autogen\".\"freezer\" WHERE (\"freezer_model\" =~ /${model_name}/) AND $timeFilter",
     "select": [
      [
       { "params": [ "temp_value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "type": "grafana-clock-panel",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 1 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Map - Realtime", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Live Temperature data",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 9 },
   "valueName": "current",
   "targets": [
    {
     "measurement": "freezer",
     "query": "SELECT \"id\", \"lat\", \"lng\", \"temp_value\",\"spoc_name\" FROM \"autogen\".\"freezer\" WHERE (\"freezer_model\" =~ /${model_name}/)  AND $timeFilter",
     "select": [
      [
       { "params": [ "id" ], "type": "field" }
      ],
      [
       { "params": [ "lat" ], "type": "field" }
      ],
      [
       { "params": [ "lng" ], "type": "field" }
      ],
      [
       { "params": [ "temp_value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Live Battery data",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 9 },
   "valueName": "current",
   "targets": [
    {
     "measurement": "freezer",
     "query": "SELECT \"id\", \"lat\", \"lng\", \"bt_value\" FROM \"autogen\".\"freezer\" WHERE (\"freezer_model\" =~ /${model_name}/) AND $timeFilter",
     "select": [
      [
       { "params": [ "id" ], "type": "field" }
      ],
      [
       { "params": [ "lat" ], "type": "field" }
      ],
      [
       { "params": [ "lng" ], "type": "field" }
      ],
      [
       { "params": [ "bt_value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  { "title": "Alert", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Temperature - Consolidated",
   "type": "graph",
   "description": "When Temperature of any sensor exceeds 5deC, a Webhook-IFTTT-Pushbullet notification will be sent to Shamshudeen Mobile",
   "gridPos": { "h": 10, "w": 19, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "yaxes": [
    { "format": "celsius", "label": "Temperature" }
   ],
   "targets": [
    {
     "alias": "ID: 5000-6000",
     "measurement": "freezer",
     "query": "SELECT \"temp_value\" FROM \"autogen\".\"freezer\" WHERE $timeFilter AND \"id\" >= 5000 AND \"id\" < 6000",
     "select": [
      [
       { "params": [ "temp_value" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "ID: 6000-7000",
     "measurement": "freezer",
     "query": "SELECT \"temp_value\" FROM \"autogen\".\"freezer\" WHERE $timeFilter AND \"id\" > 6000 AND \"id\" < 7000",
     "select": [
      [
       { "params": [ "temp_value" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "ID: 7000-8000",
     "measurement": "freezer",
     "query": "SELECT \"temp_value\" FROM \"autogen\".\"freezer\" WHERE $timeFilter AND \"id\" >= 7000 AND \"id\" < 8000",
     "select": [
      [
       { "params": [ "temp_value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Active devices",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 19, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measurement": "freezer",
     "query": "SELECT count(distinct(\"id\")) FROM \"autogen\".\"freezer\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "id" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Histogram", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 }, "repeat": "model_name" },
  {
   "title": "Histogram - Temperature",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "measurement": "freezer",
     "select": [
      [
       { "params": [ "temp_value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "type": "jdbranham-diagram-panel",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 33 },
   "options": {
    "content": "graph LR\n      Latitude --> Temperature\n      Longitude--> Temperature\n      Temperature --> Battery\n      Model --> Latitude\n      Model --> Longitude\n\n\n    "
   },
   "targets": [
    {
     "alias": "Latitude",
     "measurement": "freezer",
     "query": "SELECT \"lat\" FROM \"autogen\".\"freezer\" WHERE $timeFilter AND (\"freezer_model\" =~ /${model_name}/) ",
     "select": [
      [
       { "params": [ "lat" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Longitude",
     "measurement": "freezer",
     "select": [
      [
       { "params": [ "lng" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Temperature",
     "measurement": "freezer",
     "query": "SELECT \"temp_value\" FROM \"autogen\".\"freezer\" WHERE $timeFilter AND (\"freezer_model\" =~ /${model_name}/) ",
     "select": [
      [
       { "params": [ "temp_value" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Battery",
     "measurement": "freezer",
     "select": [
      [
       { "params": [ "bt_value" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Model",
     "measurement": "freezer",
     "query": "SELECT \"freezer_model\" FROM \"autogen\".\"freezer\" WHERE $timeFilter AND (\"freezer_model\" =~ /${model_name}/) ",
     "select": [
      [
       { "params": [ "freezer_model" ], "type": "field" }
      ]
     ]
    }
   ]
  }
 ]
}